CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."


# Model Constants
IGNORE_INDEX = -100
GRAPH_TOKEN_INDEX = -200
TEXT_TOKEN_INDEX = -300
IMAGE_TOKEN_INDEX = -400
NODE_TOKEN_INDEX = -600
DEFAULT_GRAPH_TOKEN = "<graph>"
DEFAULT_TEXT_TOKEN = "<text>"
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_NODE_TOKEN = "<feature>"
DEFAULT_GRAPH_START_TOKEN = "<GH>"
DEFAULT_GRAPH_END_TOKEN = "</GH>"
DEFAULT_TEXT_START_TOKEN = "<TX>"
DEFAULT_TEXT_END_TOKEN = "</TX>"
DEFAULT_IMAGE_START_TOKEN = "<IG>"
DEFAULT_IMAGE_END_TOKEN = "</IG>"
DEFAULT_GRAPH_PAD_ID = -500